package com.bitwiserain.pbbg.app.db.repository

import com.bitwiserain.pbbg.app.db.Transaction
import com.bitwiserain.pbbg.app.db.generated.Database
import com.bitwiserain.pbbg.app.domain.model.MyUnit

interface SquadTable {

    /**
     * Gets a single ally in a user's squad.
     */
    fun getAlly(userId: Int, allyId: Long): MyUnit?

    /**
     * Gets all allies in a user's squad.
     */
    fun getAllies(userId: Int): List<MyUnit>

    fun insertUnits(userId: Int, unitIds: Iterable<Long>)
}

// TODO: Does this actually need an autogenerated id?
class SquadTableImpl(
    private val database: Database,
    private val transaction: Transaction
) : SquadTable {

    override fun getAlly(userId: Int, allyId: Long): MyUnit? =
        database.squadQueries.getAlly(userId, allyId).executeAsOneOrNull()?.toDomainModel()

    override fun getAllies(userId: Int): List<MyUnit> =
        database.squadQueries.getAllies(userId).executeAsList().map { it.toDomainModel() }

    override fun insertUnits(userId: Int, unitIds: Iterable<Long>) = transaction {
        unitIds.forEach { unitId ->
            database.squadQueries.insertUnit(userId, unitId)
        }
    }
}
